storage_proxy: abstract_read_resolver: catch semaphore_timed_out before timed_out_error
Prepare for making semaphore_timed_out derived from timed_out_error
in seastar.  When this happens in seastar, we would need to catch
the derived, more-specific exception first to avoid the following
warning:
```
service/storage_proxy.cc:2818:18: error: exception of type 'seastar::semaphore_timed_out &' will be caught by earlier handler [-Werror,-Wexceptions]
        } catch (semaphore_timed_out&) {
                 ^
service/storage_proxy.cc:2815:18: note: for type 'seastar::timed_out_error &'
        } catch (timed_out_error&) {
                 ^
```

Later on, after the seastar change is applied to the scylla repo,
we can eliminate the duplication and catch only timed_out_error.

Test: unit(dev) (w/ the seastar changes to semaphore_timed_out
and rpc::timeout_error to inherit from timed_out_error).

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
Message-Id: <20210713132858.294504-1-bhalevy@scylladb.com>
(cherry picked from commit c8e7bd9a26a23a5ce0edae9be67eb1a4bb86b48f)